language: rust
script:
- (cd phf && cargo test)
- (cd phf && cargo test --features core)
- (cd phf_macros && cargo test --features stats)
- ./.travis/build_docs.sh
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && ./.travis/update_docs.sh
env:
  global:
    secure: H8UjXPVRBOF3peqdBwrAS1cvW4TXz9wJCwUqh5K+AP2TbFQAVt9LLkiUySVERRckR7sM/C9m8IE/nhKz7ck8+Dj7tbqd7Jef3dlienpucDF1jpbENyvsshPRvGlvd4jAQCONL9Yxs3MnRnkbr5qI3Gz/JqP7z8jzp5V5Wf7mc/I=
