[package]

name = "phf_mac"
authors = ["Steven Fackler <sfackler@gmail.com>"]
version = "0.1.0"
license = "MIT"
description = "Compiler plugin for perfect hash function data structures"

[lib]

name = "phf_mac"
path = "src/lib.rs"
plugin = true
test = false

[dependencies.phf_shared]
path = "../phf_shared"
version = "=0.1.0"

[dependencies]
time = "*"
