[package]
name = "phf_shared"
authors = ["Steven Fackler <sfackler@gmail.com>"]
version = "0.4.8"
license = "MIT"
description = "Support code shared by phf and phf_mac"
repository = "https://github.com/sfackler/rust-phf"

[lib]
name = "phf_shared"
path = "src/lib.rs"
test = false
