[package]
name = "phf_macros"
authors = ["Steven Fackler <sfackler@gmail.com>"]
version = "0.6.9"
license = "MIT"
description = "Compiler plugin for perfect hash function data structures"
repository = "https://github.com/sfackler/rust-phf"

[lib]
name = "phf_macros"
path = "src/lib.rs"
plugin = true
test = false

[features]
stats = ["time"]

[dependencies]
rand = "0.1"

[dependencies.phf_shared]
path = "../phf_shared"
version = "=0.6.9"

[dependencies.time]
version = "0.1"
optional = true
