[package]
name = "phf"
authors = ["Steven Fackler <sfackler@gmail.com>"]
version = "0.6.4"
license = "MIT"
description = "Runtime support for perfect hash function data structures"
repository = "https://github.com/sfackler/rust-phf"
documentation = "https://sfackler.github.io/doc/phf"

[lib]
name = "phf"
path = "src/lib.rs"
test = false

[features]
core = ["phf_shared/core"]

[dependencies.phf_shared]
path = "../phf_shared"
version = "=0.6.4"

[dev_dependencies.phf_macros]
path = "../phf_macros"
version = "=0.6.4"
