[package]
name = "phf"
authors = ["Steven Fackler <sfackler@gmail.com>"]
version = "0.0.1"
license = "MIT"
description = "Runtime support for perfect hash function data structures"

[lib]
name = "phf"
path = "src/lib.rs"
test = false

[dependencies.xxhash]
git = "https://github.com/Jurily/rust-xxhash"

[dev_dependencies.phf_mac]
path = "../phf_mac"
