[package]
name = "phf"
authors = ["Steven Fackler <sfackler@gmail.com>"]
version = "0.3.0"
license = "MIT"
description = "Runtime support for perfect hash function data structures"

[lib]
name = "phf"
path = "src/lib.rs"
test = false

[dependencies.phf_shared]
path = "../phf_shared"
version = "=0.3.0"

[dev_dependencies.phf_mac]
path = "../phf_mac"
version = "=0.3.0"
